version: '3.7'

services:
  drone-server:
    container_name: drone_server
    image: drone/drone:2
    networks:
      - drone
    ports:
      - "8081:80"
      - "4443:443"
    restart: always
    environment:
      DRONE_GITHUB_CLIENT_ID: ${DRONE_GITHUB_CLIENT_ID}
      DRONE_GITHUB_CLIENT_SECRET: ${DRONE_GITHUB_CLIENT_SECRET}
      DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}
      DRONE_SERVER_HOST: ${DRONE_SERVER_HOST}
      DRONE_SERVER_PROTO: ${DRONE_SERVER_PROTO}
      DRONE_DATABASE_DRIVER: ${DRONE_DATABASE_DRIVER}
      DRONE_DATABASE_DATASOURCE: postgres://${DRONE_POSTGRES_USER}:${DRONE_POSTGRES_PASS}@drone-db:5432/drone_db?sslmode=disable
      DRONE_REDIS_CONNECTION: redis://drone-redis:6379

  drone-runner:
    container_name: drone-runner
    image: drone/drone-runner-docker:linux-amd64
    privileged: true
    networks:
      - drone
    restart: always
    ports:
      - "3000:3000"
    environment: 
      - DRONE_RUNNER_NAME=${DRONE_RUNNER_NAME}
      - DRONE_RUNNER_CAPACITY=${DRONE_RUNNER_CAPACITY}
      - DRONE_RPC_HOST=${DRONE_SERVER_HOST}
      - DRONE_RPC_PROTO=${DRONE_SERVER_PROTO}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
    depends_on:
      - drone-server

  drone-db:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=${DRONE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DRONE_POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  drone-redis:
    image: redis

networks:
  drone:
    name: drone_network

volumes:
  drone_postgres_data:
    driver: local